services:
  db:
    image: postgres:16-alpine
    container_name: grav_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - grav-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

# API service abaixo 
  api:
    build: .
    container_name: grav_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    # volumes:
    #  - .:/app
    # - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run start"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - grav-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  grav-network:
    driver: bridge