name: grav-monorepo

services:
- name: backend
  github:
    repo: Gabriel-zet/Grav-monorepo
    branch: main
  source_dir: backend
  build_command: npm install && npm run build
  run_command: npm start
  http_port: 3000
  health_check:
    http_path: /health

databases:
- name: grav_db
  engine: PG
  version: "16"