# versão do node para a imagem docker (alpine é uma versão leve do linux)
FROM node:22-alpine 

WORKDIR /app

# Copia package.json e package-lock.json
COPY package*.json ./
COPY prisma ./prisma

# Instala dependências
RUN npm install --omit=dev

# Copia o resto do projeto
COPY . .

# Build do TypeScript
RUN npm run build

ENV PORT=3000
EXPOSE 3000

# Usa a imagem alpine (menor, mais rápido)
CMD ["npm", "start"]