# Usa a imagem oficial do Node.js como base
FROM node:22

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia as dependecias do projeto
COPY package*.json ./
COPY prisma ./prisma

# Instala as dependências do projeto
RUN npm install

# Copia o restante dos arquivos do projeto para o diretório de trabalho
COPY . .

RUN npm run build

# Define a variável de ambiente para a porta
ENV PORT=3000

# Expõe a porta que a aplicação irá rodar
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "start"]

